# Generated by Django 4.2.7 on 2024-01-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_category_options_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sku',)},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shu',
            new_name='sku',
        ),
    ]
